fqbn:
  - arduino:avr:uno
  - Infineon:xmc:XMC1100_XMC2GO
  - Infineon:xmc:XMC4700_Relax_Kit

arduino:avr:uno:
  port_name:    "port_serial.0"
  device:       "device.0"
  platformio:   "uno"

Infineon:xmc:XMC1100_XMC2GO:
  port_name:    "port_serial.0"
  device:       "device.0"
  platformio:   "xmc2go"

Infineon:xmc:XMC4700_Relax_Kit:
  port_name:    "port_serial.0"
  device:       "device.0"
  platformio:   "xmc4700_relax_kit"
